### ISSUE TITLE
The aplication doesn´t open

### ISSUE THREAD

**Issue by costasaiko** [NathanVaughn/msfs-mod-manager#53]
## Steps to Reproduce the Problem

  1. run installer as admin, ok
  2. Run aplication
  3.dosn´t open. it seems like crash

## Specifications

  - Application Version: `v0.5.5`
  - MSFS Edition: ( Boxed)
  - 
[debug.log](https://github.com/NathanVaughn/msfs-mod-manager/files/5826535/debug.log)

## Debug Log Contents (only if reporting a bug)

This file is found at `%APPDATA%\MSFS Mod Manager\debug.log`

(Everything after the last `__main__:<module>:27 - -----------------------` line)

```
debug log
```lib.version:get_version:32 - Attemping to determine current application version
2021-01-16 22:40:06.000 | DEBUG    | lib.version:get_version:34 - Parsing C:\Program Files (x86)\MSFS Mod Manager\base.json
2021-01-16 22:40:06.001 | DEBUG    | lib.version:get_version:38 - Version found: v0.5.5
2021-01-16 22:40:06.361 | DEBUG    | lib.theme:get_theme:10 - Getting application theme from config file
2021-01-16 22:40:06.361 | DEBUG    | lib.config:get_key_value:27 - Attempting to read key 'theme' from the main config file C:\Users\Paulo\AppData\Roaming\MSFS Mod Manager\config.ini
2021-01-16 22:40:06.362 | DEBUG    | lib.config:get_key_value:47 - Unable to find key 'theme' in config file
2021-01-16 22:40:06.362 | DEBUG    | lib.theme:get_theme:13 - FS theme is selected: False
2021-01-16 22:40:06.364 | DEBUG    | lib.theme:set_theme:19 - Writing theme selection to config file
2021-01-16 22:40:06.364 | DEBUG    | lib.config:set_key_value:57 - Attempting to write key 'theme' and value 'None' to the main config file C:\Users\Paulo\AppData\Roaming\MSFS Mod Manager\config.ini
2021-01-16 22:40:06.365 | DEBUG    | lib.config:set_key_value:66 - Section key 'settings' not found in config file, adding it
2021-01-16 22:40:06.365 | DEBUG    | lib.config:set_key_value:74 - Writing out config file
2021-01-16 22:40:06.370 | DEBUG    | lib.theme:set_theme:34 - Clearing application stylesheet
2021-01-16 22:40:06.390 | DEBUG    | lib.flight_sim:find_sim_packages_folder:176 - Attempting to automatically locate simulator path
2021-01-16 22:40:06.390 | DEBUG    | lib.flight_sim:find_sim_packages_folder:179 - Trying to find simulator path from config file
2021-01-16 22:40:06.391 | DEBUG    | lib.config:get_key_value:27 - Attempting to read key 'sim_folder' from the main config file C:\Users\Paulo\AppData\Roaming\MSFS Mod Manager\config.ini
2021-01-16 22:40:06.391 | DEBUG    | lib.config:get_key_value:36 - Section key 'settings' found in config file
2021-01-16 22:40:06.392 | DEBUG    | lib.config:get_key_value:47 - Unable to find key 'sim_folder' in config file
2021-01-16 22:40:06.392 | DEBUG    | lib.flight_sim:find_sim_packages_folder:186 - Trying to find simulator path from default Steam install
2021-01-16 22:40:06.392 | DEBUG    | lib.flight_sim:is_sim_folder:147 - Testing if C:\Users\Paulo\AppData\Roaming\Microsoft Flight Simulator is main MSFS folder
2021-01-16 22:40:06.393 | DEBUG    | lib.flight_sim:is_sim_folder:150 - Folder C:\Users\Paulo\AppData\Roaming\Microsoft Flight Simulator is main MSFS folder: False
2021-01-16 22:40:06.393 | DEBUG    | lib.flight_sim:find_sim_packages_folder:197 - Trying to find simulator path from default MS Store install
2021-01-16 22:40:06.393 | DEBUG    | lib.flight_sim:is_sim_folder:147 - Testing if C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache is main MSFS folder
2021-01-16 22:40:06.397 | DEBUG    | lib.flight_sim:is_sim_folder:150 - Folder C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache is main MSFS folder: True
2021-01-16 22:40:06.397 | DEBUG    | lib.flight_sim:parse_user_cfg:120 - Parsing UserCfg.opt file
2021-01-16 22:40:06.398 | DEBUG    | lib.flight_sim:parse_user_cfg:130 - Found InstalledPackagesPath line: InstalledPackagesPath "C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages"

2021-01-16 22:40:06.399 | DEBUG    | lib.flight_sim:parse_user_cfg:140 - Path parsed: C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages
2021-01-16 22:40:06.399 | DEBUG    | lib.flight_sim:is_sim_packages_folder:160 - Testing if C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages is MSFS sim packages folder
2021-01-16 22:40:06.400 | DEBUG    | lib.flight_sim:is_sim_packages_folder:165 - Folder C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages is MSFS sim packages folder: True
2021-01-16 22:40:06.400 | DEBUG    | lib.flight_sim:find_sim_packages_folder:209 - MS Store sim path found and valid
2021-01-16 22:40:06.400 | DEBUG    | lib.config:set_key_value:57 - Attempting to write key 'sim_folder' and value 'C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages' to the main config file C:\Users\Paulo\AppData\Roaming\MSFS Mod Manager\config.ini
2021-01-16 22:40:06.401 | DEBUG    | lib.config:set_key_value:74 - Writing out config file
2021-01-16 22:40:09.849 | DEBUG    | lib.version:check_version:92 - Checking if a new version is available
2021-01-16 22:40:09.850 | DEBUG    | lib.version:check_version_config:53 - Trying to read never version check from config file
2021-01-16 22:40:09.850 | DEBUG    | lib.config:get_key_value:27 - Attempting to read key 'never_version_check' from the main config file C:\Users\Paulo\AppData\Roaming\MSFS Mod Manager\config.ini
2021-01-16 22:40:09.852 | DEBUG    | lib.config:get_key_value:36 - Section key 'settings' found in config file
2021-01-16 22:40:09.852 | DEBUG    | lib.config:get_key_value:47 - Unable to find key 'never_version_check' in config file
2021-01-16 22:40:09.852 | DEBUG    | lib.version:check_version_config:59 - Trying to read last version check from config file
2021-01-16 22:40:09.853 | DEBUG    | lib.config:get_key_value:27 - Attempting to read key 'last_version_check' from the main config file C:\Users\Paulo\AppData\Roaming\MSFS Mod Manager\config.ini
2021-01-16 22:40:09.854 | DEBUG    | lib.config:get_key_value:36 - Section key 'settings' found in config file
2021-01-16 22:40:09.854 | DEBUG    | lib.config:get_key_value:47 - Unable to find key 'last_version_check' in config file
2021-01-16 22:40:09.855 | DEBUG    | lib.version:check_version_config:84 - Unable to read last version check from config file
2021-01-16 22:40:09.855 | DEBUG    | lib.version:check_version:102 - Attempting to open url https://api.github.com/repos/NathanVaughn/msfs-mod-manager/releases/latest
2021-01-16 22:40:11.304 | DEBUG    | lib.version:check_version:110 - Reading page contents
2021-01-16 22:40:11.305 | DEBUG    | lib.version:check_version:116 - Attemping to parse page contents
2021-01-16 22:40:11.306 | DEBUG    | lib.version:check_version:123 - Remote version found is: v0.5.5
2021-01-16 22:40:11.306 | DEBUG    | lib.version:check_version:126 - Writing out last version check time to config file
2021-01-16 22:40:11.306 | DEBUG    | lib.config:set_key_value:57 - Attempting to write key 'last_version_check' and value '2021-01-16 22:40:11' to the main config file C:\Users\Paulo\AppData\Roaming\MSFS Mod Manager\config.ini
2021-01-16 22:40:11.307 | DEBUG    | lib.config:set_key_value:74 - Writing out config file
2021-01-16 22:40:11.312 | DEBUG    | lib.version:get_version:32 - Attemping to determine current application version
2021-01-16 22:40:11.313 | DEBUG    | lib.version:get_version:34 - Parsing C:\Program Files (x86)\MSFS Mod Manager\base.json
2021-01-16 22:40:11.314 | DEBUG    | lib.version:get_version:38 - Version found: v0.5.5
2021-01-16 22:40:11.314 | DEBUG    | lib.version:check_version:151 - Remote version is not newer than local version
2021-01-16 22:40:11.343 | DEBUG    | lib.flight_sim:get_enabled_mods:387 - Retrieving list of enabled mods
2021-01-16 22:40:11.402 | DEBUG    | lib.flight_sim:parse_mod_manifest:330 - Parsing manifest for \\?\C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\152-livery-realism
2021-01-16 22:40:11.416 | DEBUG    | lib.flight_sim:parse_mod_manifest:330 - Parsing manifest for \\?\C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\A32NX
2021-01-16 22:40:11.424 | DEBUG    | lib.flight_sim:parse_mod_manifest:330 - Parsing manifest for \\?\C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\advanced-vfr-map
2021-01-16 22:40:11.424 | ERROR    | __main__:<module>:51 - Uncaught exception
Traceback (most recent call last):

> File "main.py", line 39, in <module>

  File "widgets\main_widget.py", line 662, in refresh

  File "widgets\main_widget.py", line 248, in base_action

  File "widgets\main_widget.py", line 640, in core

  File "lib\flight_sim.py", line 403, in get_enabled_mods

  File "lib\flight_sim.py", line 339, in parse_mod_manifest

**Comment by NathanVaughn** [comment]
Looking at it, it seems that the program recognizes that `advanced-vfr-map\manifest.json` exists, but it's unable to even open it to try and parse it. I downloaded the mod myself from [https://flightsim.cloud/](https://flightsim.cloud/) and had no issues on my machine. 

If you could attach that file (`C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\advanced-vfr-map\manifest.json`) to this issue, I'll see if I can figure out what's going on.

**Comment by costasaiko** [comment]
Thanks for the help, this forum don´t let attach this type file .json I opened it with word and is this:
{
  "dependencies": [],
  "content_type": "CORE",
  "title": "Advanced VFR Map",
  "manufacturer": "https://flightsim.cloud",
  "creator": "https://flightsim.cloud",
  "package_version": "0.1.0",
  "minimum_game_version": "1.12.13",
  "release_notes": {
    "neutral": {
      "LastUpdate": "",
      "OlderHistory": ""
    }
  }
}

**Comment by costasaiko** [comment]
I did uninstall that program advanced VFR and is the same problem

**Comment by costasaiko** [comment]
I think the problem is that the program automatically goes do (C:\Users\Paulo\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community). But my MSFS2020 is installed here   (D:\WpSystem\S-1-5-21-2105494446-3591955307-2415230662-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community). on the first pointer there are only links.

**Comment by NathanVaughn** [comment]
Interesting... I own the game myself on Steam and not the Microsoft Store, so this is difficult to test. I've just pushed a new version that *might* fix this. [Version 0.5.6](https://github.com/NathanVaughn/msfs-mod-manager/releases/tag/v0.5.6)
I would delete your `%APPDATA%\MSFS Mod Manager\config.ini` file before installing this version just to clear out everything.

Here's also two things to try:
1. Open up `%APPDATA%\MSFS Mod Manager\config.ini` and manually set the value of `sim_folder` to `D:\WpSystem\S-1-5-21-2105494446-3591955307-2415230662-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages` and replace what was there before.
2. Run the program as an Administrator 
3. [Take Ownership](https://www.tenforums.com/tutorials/3841-add-take-ownership-context-menu-windows-10-a.html) of the `D:\WpSystem\S-1-5-21-2105494446-3591955307-2415230662-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe` directory and see if that works with the combined above steps.

**Comment by costasaiko** [comment]
thanks I will try this

**Comment by costasaiko** [comment]
No nothing happens even did not create the profile in app

**Comment by costasaiko** [comment]
Open up %APPDATA%\MSFS Mod Manager\config.ini and manually set the value of sim_folder to D:\WpSystem\S-1-5-21-2105494446-3591955307-2415230662-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages and replace what was there before.
Run the program as an Administrator
Take Ownership of the D:\WpSystem\S-1-5-21-2105494446-3591955307-2415230662-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe directory and see if that works with the combined above steps.

Now is working, but only install by folder not instaling the .rar and give me errors from parse the d:\wp\ folder
Thank you fro your effort

**Comment by costasaiko** [comment]
[debug.log](https://github.com/NathanVaughn/msfs-mod-manager/files/5832281/debug.log)

**Comment by NathanVaughn** [comment]
I've looked into this issue more, and I really don't know what's going on. My best guess is that's it's something to do with long path names with PyInstaller, MSFS being installed from a the MS Store on a separate drive, or some symlink madness. I'm afraid I don't know how to fix this, and I think you're just going to have to install/uninstall mods manually. ¯\_(ツ)_/¯ Sorry!
